const productAttributeMap = {
  "price": [
    "priceCurrency",
    "price",
    ":price:amount",
    ":price:currency",
    "priceCurrency",
    "product-price",
    "price",
    "nowPrice",
    "product_price",
    "pdp-price",
    "ProductPriceBlock",
    "_price",
    "product_",
    "product-detail",
    "product-main ProductPriceBlock__Price",
    "priceblock_dealprice",
    "PriceBlock",
    "current-price",
    "product-price",
    "priceblock",
    "product-price",
    "ProductPrice",
    "PriceBlock",
    "dealprice",
    "__Price",
    "-price",
     "price",
    "price--",
    "price__",
    "-price",
    "Price",
    "price--large",
    "price",
  ],
  "image": [
    // check if map ->
    //  querySelectorAll(‘parent child’)[0]
    /////item prop
    "name",
    "pdp_h1",
    "og:image",

    //classes tags ........
    "image item",
    "image_grid",
    "imageGrid",
    "ImageGrid",
    "image",
    "Image",
    "pdp",
    "pdp-",
    "product-image",
    "product_image",
    "productImage",
    "ProductImage",
    "media"
    "imgTag",
    "component-media-gallery",
    "component-media",
    "product-name",
    "product-description__name",
    "productImageCarousel_image",
    "productImageCarousel",
    "imgMed",
    "productCarousel",
    "imgProduct",
    "Product"
"s7staticimage",
    ////////inner html tages
    "{parent: '.component-media' child:'img',  }",
    "{parent: '.media' child:'img',  }",
    "{parent: '.productCarousel' child:'img',  }",
    "{parent: '.product-gallery' child:'img',  }",
    "{parent: '.pdp-gallery' child:'img',  }",
    "{parent: '.s7staticimage' child:'img',  }",
    "{parent: '.productImageCarousel' child:'img',  }",
    "{parent: '.product-images' child:'img',  }",
    "{parent: '#product-gallery' child:'img',  }",
    "{parent: '#media' child:'img',  }",
    "{parent: '#productCarousel' child:'img',  }",
    "{parent: '#product-images' child:'img',  }",
    "{parent: '#pdp-gallery' child:'img',  }",
    "{parent: '#s7staticimage' child:'img',  }",
    "{parent: '#productImageCarousel' child:'img',  }",
    "{parent: 'product-' child:'img', }",
    "{parent: 'product-media' child:'img', }",
    "{parent: '.ProductImagery' child:'img',  }",
    "{parent: '.Imagery' child:'img',  }",
    "{parent: '#component-media' child:'img',  }",
    "{parent: '#ProductImagery' child:'img',  }",
    "{parent: '#Imagery' child:'img',  }",
    "{parent: '.image-grid' child:'img',  }",
    "{parent: '.imgTag' child:'img',  }",
    "{parent: '#image-grid' child:'img',  }",
    "{parent: '.image_grid' child:'img',  }",
    "{parent: '#image_grid' child:'img',  }",
    "{parent: 'ImageGrid' child:'img',  }",
    "{parent: '#ImageGrid' child:'img',  }",
    "{parent: 'imageGrid' child:'img',  }",
    "{parent: '#imageGrid' child:'img',  }",
    "{parent: '.image' child:'img',  }",
    "{parent: '#image' child:'img',  }",
    "{parent: '.Image' child:'img',  }",
    "{parent: '#Image' child:'img',  }",
    "{parent: 'pdp' child:'img',  }",
    "{parent: '.pdp' child:'img',  }",
    "{parent: '#pdp' child:'img',  }",
    "{parent: 'pdp-' child:'img',  }",
    "{parent: '.product-image' child:'img',  }",
    "{parent: '#product-image' child:'img',  }",
    "{parent: '.product_image' child:'img',  }",
    "{parent: '#product_image' child:'img',  }",
    "{parent: '.productImage' child:'img',  }",
    "{parent: '#productImage' child:'img',  }",
    "{parent: '.productImage' child:'img',  }",
    "{parent: '#productImage' child:'img',  }",
    "{parent: '#ProductImage' child:'img',  }",
    "{parent: '#ProductImage' child:'img',  }",
  ],
  "title": [
    ":name",
    "-name",
    "_name",
    "product-title",
    "product-",
    "-title",
    "product-",
    "-detail",
    "prod-",
    "pdp"
    "pdp-"
    "product-item",
    "-name",
    "product-header",
    "product_",
    "product-info",
    "-info",
    "_info",
    "__name",
    "title",
    "page-title",
    "product-detail",
    "Title",
    "item-name",
    "pdp-title",
    "product-name",
    "product_name",
    "produit_title",
    "product__title",
    "font-primary",
    "short-title",
    "page-title",
    "productName_title",
    "productName",
    "BrandTitle",
    "productBrandTitle",
    "pl-Heading",
    "pdp__heading",
    "title--",
    "page-title",
    "pl-Heading",
    "product-single__title",
    "page-title",
    "product-title",
    "product__title",
    "product-page__title",
    "__title",
    "productName_title",
    "product_title",
    "productName_title",
    "productHeading",
    "product-description",
    "pinfo__heading",
    "listing-page-title",
    "lblProductName",
    "lblProduct",
    "productTitle",
    "itemTitle",
    "title",
    "info-title",
    "hero-info-title",
  ],
};

const filters = [
  "property",
  "class",
  "itemprop",
  "item-prop",
  "id",
  "data-test-element",
  "data-test-id"
];
