class Selectors {
  static List<String> titlesQueries = [
    '[property*="og:title"]',
    '[name="og:title"]',
    '[name="twitter:title"]',
    '[name="title"]',
    'title',
    '[itemprop*="name"]',
    '[id*="product-title"]',
    '[class*="product-title"]',
    '[id*="productTitle"]',
    '[class*="productTitle"]',
    '[class*="product_title entry-title"]',
    '[class*="product"] [class*="title"]',
    '[data-test*="product-title"]',
    '[data-test*="product-"] [data-test*="-title"]',
    '[data-test*="product-name"]',
    '[class*="product-info"] [class*="title"]',
    '[class="Title"]',
    '[id*="product_title"]',
    '[class*="product_title"]',
    '[class*="Product"] [class*="_name"]',
    '[class*="product-"] [class*="-name"]',
    '[class*="product"] [class*="name"]',
    '[class*="pdp-description"]',
    '[class*="pdp"] [class*="headline"]',
    '[class*="pdp"] [class*="title"]',
    '[class*="pdp"] [class*="name"]',
  ];

  static List<String> imagesQueries = [
    '[id*="imgProduct"]',
    '[id*="imgProduct"] img',
    '[name="og:image"]',
    '[property="og:image"]',
    '[property="og:images"]',
    '[name="twitter:image"]',
    '[name="image"]',
    '[id*="imgTagWrapperId"]',
    '[class*="imgTagWrapper"]',
    '[itemprop*="image"]',
    '[class*="Product"] img',
    '[class*="ProductImagery"] img',
    '[id*="product-image"]',
    '[class*="product-image"]',
    '[class*="product-image"] img',
    '[id*="product_image"]',
    '[class*="product_image"]',
    '[class*="woocommerce-product-gallery"]',
    '[id*="productImage"]',
    '[class*="productImage"]',
    '[class*="ProductImag"] img',
    '[class*="pdp_] img',
    '[class*="pdp__gallery"] img',
    '[class*="product"] [class*="image"]',
    '[class*="product-"] [class*="-image"]',
    '[class*="product"] [class*="image"]',
    '[class*="Product"] [class*="Image"] img',
    '[class*="pdp"] [class*="image"]',
    '[class*="pdp"] [class*="img"]',
    '[class*="pdp"] img',
    '[data-test*="product-image"]',
    '[class*="image-gallery"] img',
    '[class*="image_gallery"] img',
    '[class*="imageGallery"] img',
    '[data-test*="product-"] [data-test*="-image"]',
    '[data-test*="product-image"]',
    '.image.item img',
    '[class*="product-info"] [class*="image"]',
    '[class*="Product"] [class*="_image"]',
    '[class*="MediaGallery"] img',
    '[class*="imageGrid"] img',
    '[class*="image-grid"] img',
    '[class*="thumb"] img'
  ];

  static List<String> pricesQueries = [
    '[property="og:price:amount"]',
    '[name="og:price:amount"]',
    '[data-product-attribute="price"]',
    '[data-product-price="price"]',
    '[property="og:price:amount]',
    '[name="image"]',
    '[data-id="current-price"]',
    '[itemprop="price"]',
    '[itemprop*="price"]',
    '[aria-label="Product price"]',
    '[name="twitter:data1"]',
    '[id*="product-price"]',
    '[class*="product-price"]',
    '[id*="product_price"]',
    '[class*="product_price"]',
    '[id*="ProductPrice]',
    '[class*="ProductPrice"]',
    '[id*="productPrice]',
    '[class*="woocommerce-Price-amount amount"]',
    '[class*="productPrice"]',
    '[class*="pdp-"] [class*="-price"]',
    '[class*="pdp"] [class*="price"]',
    '[class*="pdp-price"]',
    '[id*="pdp-Price]',
    '[class*="pdp-Price]',
    '[class*="Price"]',
    '[class*="product"] [class*="price"]',
    '[class*="product-"] [class*="-price"]',
    '[class*="product"] [class*="price"]',
    '[class*="Product"] [class*="Price"]',
    '[class*="pdp"] [class*="price"]',
    '[data-test*="product-price"]',
    '[class*="product-info"] [class*="price"]',
    '[class*="Product"] [class*="_price"]',
  ];
  static List<String> currencyQueries = [
    '[property="og:price:currency"]',
    '[name="og:price:currency"]',
  ];
}
